import './../css/style.css'
import ThemeContext from './../contexts/ThemeContext'
import Nav from './../layouts/index'

export const metadata = {
  title: 'vCoincheck',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const lang = undefined;
  return (
    <html lang={lang}>
      <meta
        name="google-site-verification"
        content="ARlHFWFHn8AbiaF1wlj5GZK74YmLlYlt4lGN6S9QfTI"
      />
      <body>
        <ThemeContext>
          <main>
            <div id="main-wrapper" className="show">
              <Nav ></Nav>  
              {children}
              </div>
          </main>
        </ThemeContext>
      </body>
    </html>
  )
}
